description: > # this means to ignore newlines until "baseurl:"
    Demanding, but definitely doable. Social, but educational. A focused topic, but broadly applicable skills. CS50 is the quintessential Harvard course.
email: your-email@example.com
exclude:
facebook: TODO
github: TODO
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["autolink", "hard_wrap", "no_intra_emphasis", "strikethrough", "tables", "with_toc_data"]
title: CS50x Miami
twitter: TODO
